#############################################################################
# Makefile for building: BestResidence.app/Contents/MacOS/BestResidence
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  BestResidence.pro
# Template: app
# Command: /Applications/Qt/5.6/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile BestResidence.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -F/Applications/Qt/5.6/clang_64/lib
QMAKE         = /Applications/Qt/5.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BestResidence1.0.0
DISTDIR = /Users/romainhry/Google\ Drive/L3/S6/IHM/BestResidence/BestResidence/.tmp/BestResidence1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Applications/Qt/5.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt/5.6/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		ajout.cpp \
		annoncewindow.cpp \
		annonce.cpp \
		client.cpp \
		ajoutclient.cpp \
		stats_immo.cpp \
		stats_clients.cpp \
		choix_client.cpp \
		clientwindow.cpp moc_mainwindow.cpp \
		moc_ajout.cpp \
		moc_annoncewindow.cpp \
		moc_annonce.cpp \
		moc_client.cpp \
		moc_ajoutclient.cpp \
		moc_stats_immo.cpp \
		moc_stats_clients.cpp \
		moc_choix_client.cpp \
		moc_clientwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		ajout.o \
		annoncewindow.o \
		annonce.o \
		client.o \
		ajoutclient.o \
		stats_immo.o \
		stats_clients.o \
		choix_client.o \
		clientwindow.o \
		moc_mainwindow.o \
		moc_ajout.o \
		moc_annoncewindow.o \
		moc_annonce.o \
		moc_client.o \
		moc_ajoutclient.o \
		moc_stats_immo.o \
		moc_stats_clients.o \
		moc_choix_client.o \
		moc_clientwindow.o
DIST          = annonces.xml \
		/Applications/Qt/5.6/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/lex.prf \
		BestResidence.pro mainwindow.h \
		ajout.h \
		annoncewindow.h \
		annonce.h \
		client.h \
		ajoutclient.h \
		stats_immo.h \
		stats_clients.h \
		choix_client.h \
		clientwindow.h main.cpp \
		mainwindow.cpp \
		ajout.cpp \
		annoncewindow.cpp \
		annonce.cpp \
		client.cpp \
		ajoutclient.cpp \
		stats_immo.cpp \
		stats_clients.cpp \
		choix_client.cpp \
		clientwindow.cpp
QMAKE_TARGET  = BestResidence
DESTDIR       = 
TARGET        = BestResidence.app/Contents/MacOS/BestResidence


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_ajout.h ui_ajoutclient.h ui_annoncewindow.h ui_stats_immo.h ui_stats_clients.h ui_choix_client.h ui_clientwindow.h $(OBJECTS)  
	@test -d BestResidence.app/Contents/MacOS/ || mkdir -p BestResidence.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BestResidence.pro /Applications/Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt/5.6/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt/5.6/clang_64/mkspecs/features/lex.prf \
		BestResidence.pro \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt/5.6/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/QtXml.prl \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile BestResidence.pro
/Applications/Qt/5.6/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt/5.6/clang_64/mkspecs/qdevice.pri:
/Applications/Qt/5.6/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt/5.6/clang_64/mkspecs/common/unix.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/mac.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/macx.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/sanitize.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/clang.conf:
/Applications/Qt/5.6/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt/5.6/clang_64/mkspecs/qconfig.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt/5.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt/5.6/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt/5.6/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt/5.6/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/qml_debug.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/qt.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/resources.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/moc.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/uic.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/file_copies.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt/5.6/clang_64/mkspecs/features/lex.prf:
BestResidence.pro:
/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt/5.6/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt/5.6/clang_64/lib/QtXml.framework/QtXml.prl:
/Applications/Qt/5.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile BestResidence.pro

qmake_all: FORCE

BestResidence.app/Contents/PkgInfo: 
	@test -d BestResidence.app/Contents || mkdir -p BestResidence.app/Contents
	@$(DEL_FILE) BestResidence.app/Contents/PkgInfo
	@echo "APPL????" > BestResidence.app/Contents/PkgInfo
BestResidence.app/Contents/Resources/empty.lproj: 
	@test -d BestResidence.app/Contents/Resources || mkdir -p BestResidence.app/Contents/Resources
	@touch BestResidence.app/Contents/Resources/empty.lproj
	
BestResidence.app/Contents/Info.plist: 
	@test -d BestResidence.app/Contents || mkdir -p BestResidence.app/Contents
	@$(DEL_FILE) BestResidence.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.BestResidence,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,BestResidence,g" -e "s,@LIBRARY@,BestResidence,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt/5.6/clang_64/mkspecs/macx-clang/Info.plist.app >BestResidence.app/Contents/Info.plist

all: Makefile \
		BestResidence.app/Contents/PkgInfo \
		BestResidence.app/Contents/Resources/empty.lproj \
		BestResidence.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h ajout.h annoncewindow.h annonce.h client.h ajoutclient.h stats_immo.h stats_clients.h choix_client.h clientwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp ajout.cpp annoncewindow.cpp annonce.cpp client.cpp ajoutclient.cpp stats_immo.cpp stats_clients.cpp choix_client.cpp clientwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui ajout.ui ajoutclient.ui annoncewindow.ui stats_immo.ui stats_clients.ui choix_client.ui clientwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r BestResidence.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_ajout.cpp moc_annoncewindow.cpp moc_annonce.cpp moc_client.cpp moc_ajoutclient.cpp moc_stats_immo.cpp moc_stats_clients.cpp moc_choix_client.cpp moc_clientwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_ajout.cpp moc_annoncewindow.cpp moc_annonce.cpp moc_client.cpp moc_ajoutclient.cpp moc_stats_immo.cpp moc_stats_clients.cpp moc_choix_client.cpp moc_clientwindow.cpp
moc_mainwindow.cpp: annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		mainwindow.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_ajout.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_ajout.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		ajout.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib ajout.h -o moc_ajout.cpp

moc_annoncewindow.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_annoncewindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h \
		ajout.h \
		ui_ajout.h \
		annoncewindow.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib annoncewindow.h -o moc_annoncewindow.cpp

moc_annonce.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		annonce.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib annonce.h -o moc_annonce.cpp

moc_client.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib client.h -o moc_client.cpp

moc_ajoutclient.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_ajoutclient.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		ajoutclient.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib ajoutclient.h -o moc_ajoutclient.cpp

moc_stats_immo.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_stats_immo.h \
		ui_mainwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		stats_immo.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib stats_immo.h -o moc_stats_immo.cpp

moc_stats_clients.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_stats_clients.h \
		ui_mainwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		stats_clients.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib stats_clients.h -o moc_stats_clients.cpp

moc_choix_client.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_choix_client.h \
		ui_mainwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		choix_client.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib choix_client.h -o moc_choix_client.cpp

moc_clientwindow.cpp: /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_clientwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h \
		clientwindow.h
	/Applications/Qt/5.6/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt/5.6/clang_64/mkspecs/macx-clang -I'/Users/romainhry/Google Drive/L3/S6/IHM/BestResidence/BestResidence' -I/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers -F/Applications/Qt/5.6/clang_64/lib clientwindow.h -o moc_clientwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_ajout.h ui_ajoutclient.h ui_annoncewindow.h ui_stats_immo.h ui_stats_clients.h ui_choix_client.h ui_clientwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_ajout.h ui_ajoutclient.h ui_annoncewindow.h ui_stats_immo.h ui_stats_clients.h ui_choix_client.h ui_clientwindow.h
ui_mainwindow.h: mainwindow.ui
	/Applications/Qt/5.6/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_ajout.h: ajout.ui
	/Applications/Qt/5.6/clang_64/bin/uic ajout.ui -o ui_ajout.h

ui_ajoutclient.h: ajoutclient.ui
	/Applications/Qt/5.6/clang_64/bin/uic ajoutclient.ui -o ui_ajoutclient.h

ui_annoncewindow.h: annoncewindow.ui
	/Applications/Qt/5.6/clang_64/bin/uic annoncewindow.ui -o ui_annoncewindow.h

ui_stats_immo.h: stats_immo.ui
	/Applications/Qt/5.6/clang_64/bin/uic stats_immo.ui -o ui_stats_immo.h

ui_stats_clients.h: stats_clients.ui
	/Applications/Qt/5.6/clang_64/bin/uic stats_clients.ui -o ui_stats_clients.h

ui_choix_client.h: choix_client.ui
	/Applications/Qt/5.6/clang_64/bin/uic choix_client.ui -o ui_choix_client.h

ui_clientwindow.h: clientwindow.ui
	/Applications/Qt/5.6/clang_64/bin/uic clientwindow.ui -o ui_clientwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ajout.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_ajout.h \
		annoncewindow.h \
		ui_annoncewindow.h \
		ui_mainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h \
		ajout.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_ajout.h \
		annoncewindow.h \
		ui_annoncewindow.h \
		ajoutclient.h \
		ui_ajoutclient.h \
		stats_immo.h \
		ui_stats_immo.h \
		stats_clients.h \
		ui_stats_clients.h \
		choix_client.h \
		ui_choix_client.h \
		ui_clientwindow.h \
		clientwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ajout.o: ajout.cpp /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		ajout.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_ajout.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		mainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ajout.o ajout.cpp

annoncewindow.o: annoncewindow.cpp /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		annoncewindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_annoncewindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h \
		ajout.h \
		ui_ajout.h \
		choix_client.h \
		ui_choix_client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o annoncewindow.o annoncewindow.cpp

annonce.o: annonce.cpp annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		mainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o annonce.o annonce.cpp

client.o: client.cpp client.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

ajoutclient.o: ajoutclient.cpp ajoutclient.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_ajoutclient.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ajoutclient.o ajoutclient.cpp

stats_immo.o: stats_immo.cpp /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		stats_immo.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_stats_immo.h \
		ui_mainwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stats_immo.o stats_immo.cpp

stats_clients.o: stats_clients.cpp /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		stats_clients.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_stats_clients.h \
		ui_mainwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stats_clients.o stats_clients.cpp

choix_client.o: choix_client.cpp /Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		choix_client.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_choix_client.h \
		ui_mainwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		annoncewindow.h \
		ui_annoncewindow.h \
		ajout.h \
		ui_ajout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o choix_client.o choix_client.cpp

clientwindow.o: clientwindow.cpp clientwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_clientwindow.h \
		mainwindow.h \
		annonce.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/QTableWidget \
		/Applications/Qt/5.6/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QDomDocument \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qdom.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/QtXml \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qxml.h \
		/Applications/Qt/5.6/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		client.h \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/QList \
		/Applications/Qt/5.6/clang_64/lib/QtCore.framework/Headers/qlist.h \
		ui_mainwindow.h \
		ajoutclient.h \
		ui_ajoutclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientwindow.o clientwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ajout.o: moc_ajout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ajout.o moc_ajout.cpp

moc_annoncewindow.o: moc_annoncewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_annoncewindow.o moc_annoncewindow.cpp

moc_annonce.o: moc_annonce.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_annonce.o moc_annonce.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

moc_ajoutclient.o: moc_ajoutclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ajoutclient.o moc_ajoutclient.cpp

moc_stats_immo.o: moc_stats_immo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stats_immo.o moc_stats_immo.cpp

moc_stats_clients.o: moc_stats_clients.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stats_clients.o moc_stats_clients.cpp

moc_choix_client.o: moc_choix_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_choix_client.o moc_choix_client.cpp

moc_clientwindow.o: moc_clientwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientwindow.o moc_clientwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

